### ISSUE TITLE
Commit

### ISSUE THREAD

**Issue by KESEU** [mendix/docs#4604]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Commit](https://docs.mendix.com/refguide/commit-dialog/)

Document link: [commit-dialog.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/menus/version-control-menu/commit-dialog.md)

## My Issue/Suggestion

Hello,

I'm kind of new to this low-code app so I was doing the "Become a Rapid Developper" Course,

And managed to get this error on 7.7.6 (Commit your work using Mendix App Pro)

{
Mendix.Modeler.VersionControl.VersionControlException: An error occurred while checking for changes on disk.
 ---> SharpSvn.SvnRepositoryIOException: Unable to connect to a repository at URL 'https://teamserver.sprintr.com/60388532-b2b9-4954-ad63-59f21e734616/trunk'
 ---> SharpSvn.SvnRepositoryIOForbiddenException: Access to '/60388532-b2b9-4954-ad63-59f21e734616/trunk' forbidden
   --- End of inner exception stack trace ---
   at SharpSvn.SvnClientArgs.HandleResult(SvnClientContext client, SvnException error, Object targets)
   at SharpSvn.SvnClient.Status(String path, SvnStatusArgs args, EventHandler`1 statusHandler)
   at SharpSvn.SvnClient.GetStatus(String path, SvnStatusArgs args, Collection`1& statuses)
   at Mendix.Modeler.VersionControl.SvnClientAdapter.GetStatus(String path, SvnStatusArgs args, Collection`1& statuses) in C:\Users\Autobuild\workspace\AppStudio4.0-Build\modeler\Mendix.Modeler.VersionControl\Svn\SvnClientAdapter.cs:line 47
   at Mendix.Modeler.VersionControl.Windows.SvnConnector.<>c__DisplayClass13_0.<GetChanges>b__0(ISvnClient c) in C:\Users\Autobuild\workspace\AppStudio4.0-Build\modeler\Mendix.Modeler.VersionControl.Windows\Svn\SvnConnector.cs:line 160
   at Mendix.Modeler.VersionControl.Windows.SvnConnector.PathClientDo(String workingCopyPath, Action`1 action) in C:\Users\Autobuild\workspace\AppStudio4.0-Build\modeler\Mendix.Modeler.VersionControl.Windows\Svn\SvnConnector.cs:line 339
   at Mendix.Modeler.VersionControl.Windows.SvnConnector.GetChanges(String localDir, Boolean retrieveRemoteChanges, Boolean retrieveAllEntries) in C:\Users\Autobuild\workspace\AppStudio4.0-Build\modeler\Mendix.Modeler.VersionControl.Windows\Svn\SvnConnector.cs:line 160
   --- End of inner exception stack trace ---
   at Mendix.Modeler.VersionControl.Windows.SvnConnector.GetChanges(String localDir, Boolean retrieveRemoteChanges, Boolean retrieveAllEntries) in C:\Users\Autobuild\workspace\AppStudio4.0-Build\modeler\Mendix.Modeler.VersionControl.Windows\Svn\SvnConnector.cs:line 166
   at Mendix.Modeler.VersionControl.Operations.Svn.SvnCheckWorkingCopyOperation.CheckWorkingCopy(String projectDirectory) in C:\Users\Autobuild\workspace\AppStudio4.0-Build\modeler\Mendix.Modeler.VersionControl\Operations\Svn\SvnCheckWorkingCopyOperation.cs:line 45
}

Thank you even if you can't help me on this :)

**Comment by johannahemminger** [comment]
Hi @KESEU , thanks for raising this issue. Did you find a solution for it? There might be some related information the Mendix forums (forum.mendix.com), or you can raise a ticket with Support if you are a paying customer.

**Comment by johannahemminger** [comment]
Hi @KESEU , I haven't heard back from you, so I hope you have resolved your error. I'm going to mark this as closed, but please feel free to open another issue if you have any suggestions for improvement for our documentation, or check out the Mendix Forum or Mendix support if you run into other issues. Thanks again!
